# Experiment Prep Configuration
# Operational parameters only - paths come from ../.env

experiments:
  exp1_sequence_fold:
    type: "sequence"
    k_folds: 10
    stratify_by: "species_resolution"  # Column from BLAST output
    seed: 42
    
  exp2_species_fold:
    type: "species_group"
    k_folds: 10
    stratify_by: "genus"
    seed: 42

debug_subset:
  enabled: true
  n_genera: 5
  min_species_per_genus: 2  # Lowered from 3 for conservative datasets
  target_size: 10000
  seed: 42
  # Note: Debug subsets should be used with smaller models
  # e.g., reduce embedding_dim, num_layers, num_heads for transformers
  # This allows testing on cheaper GPUs (T4 instead of A100)